language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-23.0.1

before_install:
 - chmod +x gradlew
 - touch local.properties

script: ./gradlew build